--@/home/fulcrum/BSUIR/MDISUBD/LR2/test2.sql

INSERT INTO GROUPS (NAME) VALUES ('Group A');
INSERT INTO GROUPS (NAME) VALUES ('Group B');
INSERT INTO GROUPS (ID, NAME) VALUES (1, 'Group C');
INSERT INTO GROUPS (ID, NAME) VALUES (1, 'Group D');
INSERT INTO STUDENTS (NAME, GROUP_ID) VALUES ('Alice', (SELECT ID FROM GROUPS WHERE NAME = 'Group A' ));
INSERT INTO STUDENTS (NAME, GROUP_ID) VALUES ('Bob', (SELECT ID FROM GROUPS WHERE NAME = 'Group A' ));
INSERT INTO STUDENTS (NAME, GROUP_ID) VALUES ('Jhon', (SELECT ID FROM GROUPS WHERE NAME = 'Group B' ));
INSERT INTO STUDENTS (NAME, GROUP_ID) VALUES ('Bran', (SELECT ID FROM GROUPS WHERE NAME = 'Group B' ));
INSERT INTO STUDENTS (NAME, GROUP_ID) VALUES ('ERIK', (SELECT ID FROM GROUPS WHERE NAME = 'Group B' ));
INSERT INTO STUDENTS (NAME, GROUP_ID) VALUES ('MAVERIK', (SELECT ID FROM GROUPS WHERE NAME = 'Group B' ));
SELECT * FROM GROUPS;

SELECT * FROM STUDENTS;

SELECT * FROM STUDENTS_LOG;

